Project: Rsipac_CR
Experiment:
  name: &name NAF_CR_Trans_aug_2:1
  checkpoint_dir: !!python/object/apply:os.path.join ["./experiments", *name, "checkpoints"]
  result_dir: !!python/object/apply:os.path.join ["./experiments", *name, "results"]
  log_dir:
  resume:
#    resume_epoch: 50
#    resume_ckpt: checkpoint_epoch_100.pth
#    resume_wandb: 16q8xi38
#    resume_addition: true  # modification max epoch

manual_seed: 42
Accelerator:
  gradient_accumulation_steps: 1


datasets:
  train:
    name: Real_CR
    phase: train
    root:  ../Dataset/Rsipac/train_256
    meta_info: ../Dataset/Rsipac/train_256/train_val_list.csv
    io_backend:
      type: disk

    # image settings
    use_cloudmask: false
    cloud_threshold: 0.2
    random_crop: true
    base_size: 256
    crop_size: 192
    use_flip: true
    use_rot: true

    # dataloader
    batch_size: 4
    use_shuffle: true

  val:
    name: Real_CR
    phase: val
    root: ../Dataset/Rsipac/train_256
    meta_info: ../Dataset/Rsipac/train_256/train_val_list.csv
    io_backend:
      type: disk

    # image settings
    use_cloudmask: false
    cloud_threshold: 0.2
    random_crop: false
    base_size: 256
    crop_size: 256
    # dataloader
    batch_size: 4

#  val_2:
network_g:
  name: NAF_Trans_Net
  img_channel: 2
  output_channel: 3

  width: 64
  dw_expand: 2
  ffn_expand: 2
  middle_blk_num: 1
  enc_blk_nums: [1, 1, 1, 28] # 28
  dec_blk_nums: [1, 1, 1, 1]

train:
  epochs: 150
  optimizer_g:
    type: AdamW
    args:
      lr: !!float 1e-3
      weight_decay: 0.
      betas: [0.9, 0.9]
  scheduler:
    type: TrueCosineAnnealingLR
    args:
      T_max: 150  # step
      eta_min: !!float 1e-7
  loss_funs:
    pixel: l1
    ssim: ms_ssim
  loss_weights: [1, 2]

save_epoch_freq: 10
log_step_freq: 100
visual_step_freq: 1000
valid_visual_step_freq: 1000

